version: '3.8'

services:
  rose-glass-dream:
    build: 
      context: ..
      dockerfile: web/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/rose-glass
      - DEFAULT_LLM=claude
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped